package com.partners.entity;

import java.sql.Timestamp;

/**
 * Autofrequencyhistory generated by hbm2java
 */
public class Autofrequencyhistory implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int autoFrequencyId;
	private int weatherStaionTerminalId;
	private int autoFrequency;
	private int weatherStationId;
	private Timestamp createDate;
	private String autoFrequencyUnit;
	public int getAutoFrequencyId() {
		return autoFrequencyId;
	}
	public void setAutoFrequencyId(int autoFrequencyId) {
		this.autoFrequencyId = autoFrequencyId;
	}
	public int getAutoFrequency() {
		return autoFrequency;
	}
	public void setAutoFrequency(int autoFrequency) {
		this.autoFrequency = autoFrequency;
	}
	public Timestamp getCreateDate() {
		return createDate;
	}
	public void setCreateDate(Timestamp createDate) {
		this.createDate = createDate;
	}
	public String getAutoFrequencyUnit() {
		return autoFrequencyUnit;
	}
	public void setAutoFrequencyUnit(String autoFrequencyUnit) {
		this.autoFrequencyUnit = autoFrequencyUnit;
	}
	public int getWeatherStationId() {
		return weatherStationId;
	}
	public void setWeatherStationId(int weatherStationId) {
		this.weatherStationId = weatherStationId;
	}
	public int getWeatherStaionTerminalId() {
		return weatherStaionTerminalId;
	}
	public void setWeatherStaionTerminalId(int weatherStaionTerminalId) {
		this.weatherStaionTerminalId = weatherStaionTerminalId;
	}
 
}
