package com.partners.entity;
// Generated May 30, 2017 9:47:29 PM by Hibernate Tools 3.5.0.Final

/**
 * Emalilandsmssettings generated by hbm2java
 */
public class Emalilandsmssettings extends BaseEntity  implements java.io.Serializable {

	private Integer emalilSettingsId;
	private String smtpserver;
	private String smtpuserName;
	private String smtpuserPwd;
	private String receiveEmail;
	private String smsurl;
	private String smsuserName;
	private String smsuserPwd;
	private String smsphone;
	private Character extendInfo;
	private String uniqueId;
	public Integer getEmalilSettingsId() {
		return this.emalilSettingsId;
	}

	public void setEmalilSettingsId(Integer emalilSettingsId) {
		this.emalilSettingsId = emalilSettingsId;
	}

	public String getSmtpserver() {
		return this.smtpserver;
	}

	public void setSmtpserver(String smtpserver) {
		this.smtpserver = smtpserver;
	}

	public String getSmtpuserName() {
		return this.smtpuserName;
	}

	public void setSmtpuserName(String smtpuserName) {
		this.smtpuserName = smtpuserName;
	}

	public String getSmtpuserPwd() {
		return this.smtpuserPwd;
	}

	public void setSmtpuserPwd(String smtpuserPwd) {
		this.smtpuserPwd = smtpuserPwd;
	}

	public String getReceiveEmail() {
		return this.receiveEmail;
	}

	public void setReceiveEmail(String receiveEmail) {
		this.receiveEmail = receiveEmail;
	}

	public String getSmsurl() {
		return this.smsurl;
	}

	public void setSmsurl(String smsurl) {
		this.smsurl = smsurl;
	}

	public String getSmsuserName() {
		return this.smsuserName;
	}

	public void setSmsuserName(String smsuserName) {
		this.smsuserName = smsuserName;
	}

	public String getSmsuserPwd() {
		return this.smsuserPwd;
	}

	public void setSmsuserPwd(String smsuserPwd) {
		this.smsuserPwd = smsuserPwd;
	}

	public String getSmsphone() {
		return this.smsphone;
	}

	public void setSmsphone(String smsphone) {
		this.smsphone = smsphone;
	}

	public Character getExtendInfo() {
		return this.extendInfo;
	}

	public void setExtendInfo(Character extendInfo) {
		this.extendInfo = extendInfo;
	}

	public String getUniqueId() {
		return uniqueId;
	}

	public void setUniqueId(String uniqueId) {
		this.uniqueId = uniqueId;
	}
	
}
