package com.partners.entity;
// Generated May 30, 2017 9:47:29 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Fileformat generated by hbm2java
 */
public class Fileformat extends BaseEntity  implements java.io.Serializable {

	private Integer fileFormatId;
	private String fileFormatName;
	private String fileFormat;
	private Character extendInfo;

	public Fileformat() {
	}

	public Integer getFileFormatId() {
		return this.fileFormatId;
	}

	public void setFileFormatId(Integer fileFormatId) {
		this.fileFormatId = fileFormatId;
	}

	public String getFileFormatName() {
		return this.fileFormatName;
	}

	public void setFileFormatName(String fileFormatName) {
		this.fileFormatName = fileFormatName;
	}

	public String getFileFormat() {
		return this.fileFormat;
	}

	public void setFileFormat(String fileFormat) {
		this.fileFormat = fileFormat;
	}

	public Character getExtendInfo() {
		return this.extendInfo;
	}

	public void setExtendInfo(Character extendInfo) {
		this.extendInfo = extendInfo;
	}


}
