package com.partners.entity;
// Generated May 30, 2017 9:47:29 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * Filepushsetting generated by hbm2java
 */
public class Filepushsetting extends BaseEntity  implements java.io.Serializable {

	private Integer filePushSettingId;
	private String filePushSettingName;
	private String host;
	private byte port;
	private byte protocol;
	private String userName;
	private String userPwd;
	private String uploadPath;
	private byte isDisabled;
	private Date schedultDate;
	private byte isUploadNow;
	private String weatherStationSettings;
	private String fileFormatSettings;
	private Character extendInfo;

	public Integer getFilePushSettingId() {
		return this.filePushSettingId;
	}

	public void setFilePushSettingId(Integer filePushSettingId) {
		this.filePushSettingId = filePushSettingId;
	}

	public String getFilePushSettingName() {
		return this.filePushSettingName;
	}

	public void setFilePushSettingName(String filePushSettingName) {
		this.filePushSettingName = filePushSettingName;
	}

	public String getHost() {
		return this.host;
	}

	public void setHost(String host) {
		this.host = host;
	}

	public byte getPort() {
		return this.port;
	}

	public void setPort(byte port) {
		this.port = port;
	}

	public byte getProtocol() {
		return this.protocol;
	}

	public void setProtocol(byte protocol) {
		this.protocol = protocol;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserPwd() {
		return this.userPwd;
	}

	public void setUserPwd(String userPwd) {
		this.userPwd = userPwd;
	}

	public String getUploadPath() {
		return this.uploadPath;
	}

	public void setUploadPath(String uploadPath) {
		this.uploadPath = uploadPath;
	}

	public byte getIsDisabled() {
		return this.isDisabled;
	}

	public void setIsDisabled(byte isDisabled) {
		this.isDisabled = isDisabled;
	}

	public Date getSchedultDate() {
		return this.schedultDate;
	}

	public void setSchedultDate(Date schedultDate) {
		this.schedultDate = schedultDate;
	}

	public byte getIsUploadNow() {
		return this.isUploadNow;
	}

	public void setIsUploadNow(byte isUploadNow) {
		this.isUploadNow = isUploadNow;
	}

	public String getWeatherStationSettings() {
		return this.weatherStationSettings;
	}

	public void setWeatherStationSettings(String weatherStationSettings) {
		this.weatherStationSettings = weatherStationSettings;
	}

	public String getFileFormatSettings() {
		return this.fileFormatSettings;
	}

	public void setFileFormatSettings(String fileFormatSettings) {
		this.fileFormatSettings = fileFormatSettings;
	}

	public Character getExtendInfo() {
		return this.extendInfo;
	}

	public void setExtendInfo(Character extendInfo) {
		this.extendInfo = extendInfo;
	}

}
