package com.partners.entity;
// Generated May 30, 2017 9:47:29 PM by Hibernate Tools 3.5.0.Final

/**
 * Grouppermission generated by hbm2java
 */
public class Grouppermission extends BaseEntity  implements java.io.Serializable {

	private static final long serialVersionUID = -816870936117975894L;
	private Integer groupPermissionId;
	private Integer groupId;
	private Integer permissionId;

	public Integer getGroupPermissionId() {
		return groupPermissionId;
	}

	public void setGroupPermissionId(Integer groupPermissionId) {
		this.groupPermissionId = groupPermissionId;
	}

	public Integer getGroupId() {
		return groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	public Integer getPermissionId() {
		return permissionId;
	}

	public void setPermissionId(Integer permissionId) {
		this.permissionId = permissionId;
	}
}
