package com.partners.entity;
// Generated May 30, 2017 9:47:29 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * Manualsyncsettings generated by hbm2java
 */
public class Manualsyncsettings extends BaseEntity implements java.io.Serializable {

	private Integer manualSyncSettingsId;
	private Date startDate;
	private Date endDate;
	private String terminalInstruction;
	private byte protocol;
	private String userName;
	private String userPwd;
	private String uploadPath;
	private byte isDisabled;
	private Date schedultDate;
	private byte isUploadNow;
	private String weatherStationSettings;
	private String fileFormatSettings;
	private Character extendInfo;

	public Integer getManualSyncSettingsId() {
		return this.manualSyncSettingsId;
	}

	public void setManualSyncSettingsId(Integer manualSyncSettingsId) {
		this.manualSyncSettingsId = manualSyncSettingsId;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getTerminalInstruction() {
		return this.terminalInstruction;
	}

	public void setTerminalInstruction(String terminalInstruction) {
		this.terminalInstruction = terminalInstruction;
	}

	public byte getProtocol() {
		return this.protocol;
	}

	public void setProtocol(byte protocol) {
		this.protocol = protocol;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserPwd() {
		return this.userPwd;
	}

	public void setUserPwd(String userPwd) {
		this.userPwd = userPwd;
	}

	public String getUploadPath() {
		return this.uploadPath;
	}

	public void setUploadPath(String uploadPath) {
		this.uploadPath = uploadPath;
	}

	public byte getIsDisabled() {
		return this.isDisabled;
	}

	public void setIsDisabled(byte isDisabled) {
		this.isDisabled = isDisabled;
	}

	public Date getSchedultDate() {
		return this.schedultDate;
	}

	public void setSchedultDate(Date schedultDate) {
		this.schedultDate = schedultDate;
	}

	public byte getIsUploadNow() {
		return this.isUploadNow;
	}

	public void setIsUploadNow(byte isUploadNow) {
		this.isUploadNow = isUploadNow;
	}

	public String getWeatherStationSettings() {
		return this.weatherStationSettings;
	}

	public void setWeatherStationSettings(String weatherStationSettings) {
		this.weatherStationSettings = weatherStationSettings;
	}

	public String getFileFormatSettings() {
		return this.fileFormatSettings;
	}

	public void setFileFormatSettings(String fileFormatSettings) {
		this.fileFormatSettings = fileFormatSettings;
	}

	public Character getExtendInfo() {
		return this.extendInfo;
	}

	public void setExtendInfo(Character extendInfo) {
		this.extendInfo = extendInfo;
	}
}
