package com.partners.entity;
// Generated May 30, 2017 9:47:29 PM by Hibernate Tools 3.5.0.Final

import lombok.Data;
import lombok.experimental.SuperBuilder;

import java.util.Date;

/**
 * Notification generated by hbm2java
 */
@SuperBuilder
public class Notification extends BaseEntity implements java.io.Serializable {

	private Integer notificationId;
	private int notificationType;
	private String notificationDesc;
	private String message;
	private byte isChecked;
	private Character extendInfo;

	public Integer getNotificationId() {
		return this.notificationId;
	}

	public void setNotificationId(Integer notificationId) {
		this.notificationId = notificationId;
	}

	public int getNotificationType() {
		return this.notificationType;
	}

	public void setNotificationType(int notificationType) {
		this.notificationType = notificationType;
	}

	public String getNotificationDesc() {
		return this.notificationDesc;
	}

	public void setNotificationDesc(String notificationDesc) {
		this.notificationDesc = notificationDesc;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public byte getIsChecked() {
		return this.isChecked;
	}

	public void setIsChecked(byte isChecked) {
		this.isChecked = isChecked;
	}

	public Character getExtendInfo() {
		return this.extendInfo;
	}

	public void setExtendInfo(Character extendInfo) {
		this.extendInfo = extendInfo;
	}
}
