package com.partners.entity;
// Generated May 30, 2017 9:47:29 PM by Hibernate Tools 3.5.0.Final

/**
 * Permission generated by hbm2java
 */
public class Permission implements java.io.Serializable {

	private static final long serialVersionUID = -7620321418787408369L;
	private int permissionId;
	private String permissionName;
	private String permissionDesc;
	private byte isOnlySystemPremission;
	private int parentId;
	private boolean hasChild;
	private int OrderId;	
	private String URL;		
	private int enabled;		
	private String ICON;		
	public int getIsNavigation() {
		return isNavigation;
	}
	public void setIsNavigation(int isNavigation) {
		this.isNavigation = isNavigation;
	}
	private int isNavigation;	
	public String getURL() {
		return URL;
	}
	public void setURL(String uRL) {
		URL = uRL;
	}
	public int getParentId() {
		return parentId;
	}
	public void setParentId(int parentId) {
		this.parentId = parentId;
	}

	public int getPermissionId() {
		return this.permissionId;
	}

	public void setPermissionId(int permissionId) {
		this.permissionId = permissionId;
	}

	public String getPermissionName() {
		return this.permissionName;
	}

	public void setPermissionName(String permissionName) {
		this.permissionName = permissionName;
	}

	public String getPermissionDesc() {
		return this.permissionDesc;
	}

	public void setPermissionDesc(String permissionDesc) {
		this.permissionDesc = permissionDesc;
	}

	public byte getIsOnlySystemPremission() {
		return this.isOnlySystemPremission;
	}

	public void setIsOnlySystemPremission(byte isOnlySystemPremission) {
		this.isOnlySystemPremission = isOnlySystemPremission;
	}
	public boolean isHasChild() {
		return hasChild;
	}
	public void setHasChild(boolean hasChild) {
		this.hasChild = hasChild;
	}
	public int getOrderId() {
		return OrderId;
	}
	public void setOrderId(int orderId) {
		OrderId = orderId;
	}
	public int getEnabled() {
		return enabled;
	}
	public void setEnabled(int enabled) {
		this.enabled = enabled;
	}
	public String getICON() {
		return ICON;
	}
	public void setICON(String iCON) {
		ICON = iCON;
	}

}
