package com.partners.entity;
// Generated May 30, 2017 9:47:29 PM by Hibernate Tools 3.5.0.Final

import java.sql.Timestamp;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * Schedulehistory generated by hbm2java
 */
public class Schedulehistory extends BaseEntity  implements java.io.Serializable {

	private Integer scheduleHistoryId;
	private int taskId;
	private byte taskType;
	private String taskDesc;
	private Timestamp taskStartDate;
	private Timestamp taskEndDate;
	private byte taskResult;
	private String taskMessage;
	private Character extendInfo;

	public Integer getScheduleHistoryId() {
		return this.scheduleHistoryId;
	}

	public void setScheduleHistoryId(Integer scheduleHistoryId) {
		this.scheduleHistoryId = scheduleHistoryId;
	}

	public int getTaskId() {
		return this.taskId;
	}

	public void setTaskId(int taskId) {
		this.taskId = taskId;
	}

	public byte getTaskType() {
		return this.taskType;
	}

	public void setTaskType(byte taskType) {
		this.taskType = taskType;
	}

	public String getTaskDesc() {
		return this.taskDesc;
	}

	public void setTaskDesc(String taskDesc) {
		this.taskDesc = taskDesc;
	}
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
	public Timestamp getTaskStartDate() {
		return this.taskStartDate;
	}

	public void setTaskStartDate(Timestamp taskStartDate) {
		this.taskStartDate = taskStartDate;
	}
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
	public Timestamp getTaskEndDate() {
		return this.taskEndDate;
	}

	public void setTaskEndDate(Timestamp taskEndDate) {
		this.taskEndDate = taskEndDate;
	}

	public byte getTaskResult() {
		return this.taskResult;
	}

	public void setTaskResult(byte taskResult) {
		this.taskResult = taskResult;
	}

	public String getTaskMessage() {
		return this.taskMessage;
	}

	public void setTaskMessage(String taskMessage) {
		this.taskMessage = taskMessage;
	}

	public Character getExtendInfo() {
		return this.extendInfo;
	}

	public void setExtendInfo(Character extendInfo) {
		this.extendInfo = extendInfo;
	}
}
