package com.partners.entity;
// Generated May 30, 2017 9:47:29 PM by Hibernate Tools 3.5.0.Final

/**
 * Usergroup generated by hbm2java
 */
public class Usergroup extends BaseEntity implements java.io.Serializable {

	private int groupId;
	private String groupUniqueId;
	private String groupName;
	private String stationGroup;
	private String station;

	public String getGroupUniqueId() {
		return groupUniqueId;
	}

	public void setGroupUniqueId(String groupUniqueId) {
		this.groupUniqueId = groupUniqueId;
	}

	public int getGroupId() {
		return groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	public String getGroupName() {
		return groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public String getStationGroup() {
		return stationGroup;
	}

	public void setStationGroup(String stationGroup) {
		this.stationGroup = stationGroup;
	}

	public String getStation() {
		return station;
	}

	public void setStation(String station) {
		this.station = station;
	}

}
