package com.partners.entity;
// Generated May 30, 2017 9:47:29 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * Weatherstationfilesetting generated by hbm2java
 */
public class Weatherstationfilesetting extends BaseEntity implements java.io.Serializable {

	private Integer wsfid;
	private Weatherstation weatherstation;
	private Fileformat fileformat;

	public Integer getWsfid() {
		return this.wsfid;
	}

	public void setWsfid(Integer wsfid) {
		this.wsfid = wsfid;
	}

	public Weatherstation getWeatherstation() {
		return this.weatherstation;
	}

	public void setWeatherstation(Weatherstation weatherstation) {
		this.weatherstation = weatherstation;
	}

	public Fileformat getFileformat() {
		return this.fileformat;
	}

	public void setFileformat(Fileformat fileformat) {
		this.fileformat = fileformat;
	}
}
