package com.partners.view.entity;
// Generated May 30, 2017 9:47:29 PM by Hibernate Tools 3.5.0.Final

import java.sql.Timestamp;

/**
 * Usergroup generated by hbm2java
 */
public class VUserGroup extends vBaseEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -929594699878077184L;
	private int groupId;
	private String groupName;
	private int[] permissions;
	private String groupUniqueId;
	private String weatherCategory;
	private String weatherStation;
	public String getGroupUniqueId() {
		return groupUniqueId;
	}

	public void setGroupUniqueId(String groupUniqueId) {
		this.groupUniqueId = groupUniqueId;
	}

	public int[] getPermissions() {
		return permissions;
	}

	public void setPermissions(int[] permissions) {
		this.permissions = permissions;
	}

	public VUserGroup() {
	}
	public VUserGroup(vBaseEntity entity) {
		super(entity);
	}
	
	public VUserGroup(int groupId, String groupName, Timestamp createDate, String orderField, String orderType, int startIndex, int size) {
		super(createDate,groupName,groupId, orderField,orderType,startIndex,size);
		this.groupId = groupId;	
	}

	public int getGroupId() {
		return groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	public String getGroupName() {
		return groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public String getWeatherCategory() {
		return weatherCategory;
	}

	public void setWeatherCategory(String weatherCategory) {
		this.weatherCategory = weatherCategory;
	}

	public String getWeatherStation() {
		return weatherStation;
	}

	public void setWeatherStation(String weatherStation) {
		this.weatherStation = weatherStation;
	}
	
}
